### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by nousername33** [SolidBlock-cn/BRRP#3]
^^^

**Comment by SolidBlock-cn** [comment]
Please provide the log or crash report so that I can locate the problem and fix it. Otherwise the thread will be closed as invalid.

**Comment by SolidBlock-cn** [comment]
As there is no detailed information, this issue will be closed.

**Comment by nousername33** [comment]
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) ~[fabric-loader-0.14.12.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:30) ~[memoryleakfix-1.19-0.7.0.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bad000$onFinishedLoadingWorlds(MinecraftServer.java:5765) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:331) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:637) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Registry is already frozen
	at net.minecraft.class_2370.method_40269(class_2370.java:365) ~[server-intermediary.jar:?]
	at net.minecraft.class_2248.<init>(class_2248.java:74) ~[server-intermediary.jar:?]
	at net.devtech.arrp.generator.BRRPCubeBlock.<init>(BRRPCubeBlock.java:29) ~[brrp-fabric-0.8.2-1.19.2.jar:?]
	at net.devtech.arrp.generator.BRRPCubeBlock.cubeAll(BRRPCubeBlock.java:42) ~[brrp-fabric-0.8.2-1.19.2.jar:?]
	at net.devtech.arrp.BRRPDevelopment.<clinit>(BRRPDevelopment.java:54) ~[brrp-fabric-0.8.2-1.19.2.jar:?]


**Comment by SolidBlock-cn** [comment]
It seems strange. The class `BRRPDevelopment` should not be loaded outside of the development environment. I guess you installed OptiFine?

**Comment by SolidBlock-cn** [comment]
It seems strange. The class `BRRPDevelopment` should not be loaded outside of the development environment. I guess you installed OptiFine?

**Comment by nousername33** [comment]
On a server? No optifine. We have starlight though.

**Comment by SolidBlock-cn** [comment]
Do you have more information about the crash? Such as the stacktrace after the `at net.devtech.arrp.BRRPDevelopment.(BRRPDevelopment.java:54)`?

**Comment by nousername33** [comment]
What exactly is a stacktrace? I can give you a crash report though.

**Comment by SolidBlock-cn** [comment]
Seems duplicate with #5 and #6 .

**Comment by SolidBlock-cn** [comment]
I've tested my latest version on the dedicated server of Fabric. Please try the latest 0.9.0 version.
